'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Reports

    Partial Public Class Packages

        '''<summary>
        '''PackagesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PackagesLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''PackagesGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PackagesGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''imgBuiltIn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBuiltIn As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''BuiltInAddInNotice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BuiltInAddInNotice As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''InstallVisualizerLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InstallVisualizerLink As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''InstallDataSourceLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InstallDataSourceLink As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
