'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Reports

    Partial Public Class Settings

        '''<summary>
        '''dshDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshDataSource As Global.System.Web.UI.UserControl

        '''<summary>
        '''DataSourceSection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataSourceSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ReportsSettingsMultiView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportsSettingsMultiView As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''AccessDeniedView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AccessDeniedView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''ErrorImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''ErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SuperUserView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SuperUserView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''WarningImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WarningImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''WarningMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WarningMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tblDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDataSource As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblParameters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblParameters As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtParameters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtParameters As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDataSource As Global.System.Web.UI.UserControl

        '''<summary>
        '''DataSourceDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataSourceDropDown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DataSourceSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataSourceSettings As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''DataSourceNotConfiguredView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataSourceNotConfiguredView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''DataSourceNotConfiguredImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataSourceNotConfiguredImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''DataSourceNotConfiguredLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataSourceNotConfiguredLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnTestDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTestDataSource As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''btnShowXml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnShowXml As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''rowResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''imgQueryResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgQueryResults As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblQueryResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQueryResults As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnHideTestResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHideTestResults As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''rowXmlSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowXmlSource As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblXmlSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblXmlSource As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtXmlSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtXmlSource As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnHideXmlSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHideXmlSource As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dshConvertersSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshConvertersSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''ConvertersSection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConvertersSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblHtmlDecode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHtmlDecode As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlDecode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlDecode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblHtmlEncode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHtmlEncode As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlEncode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlEncode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshVisualizerSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshVisualizerSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''VisualizerSettingsOuter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VisualizerSettingsOuter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCacheDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCacheDuration As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkCaching control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCaching As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''spanCacheDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spanCacheDuration As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCacheDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCacheDuration As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CacheWarningImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CacheWarningImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''CacheWarningLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CacheWarningLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblShowInfoPane control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowInfoPane As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowInfoPane control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowInfoPane As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblShowControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowControls As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowControls As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAutoRunReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAutoRunReport As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAutoRunReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoRunReport As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTokenReplace control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTokenReplace As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkTokenReplace control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTokenReplace As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblVisualizer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVisualizer As Global.System.Web.UI.UserControl

        '''<summary>
        '''VisualizerDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VisualizerDropDown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''VisualizerSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VisualizerSettings As Global.System.Web.UI.WebControls.MultiView
    End Class
End Namespace
