'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Reports

    Partial Public Class ViewReports

        '''<summary>
        '''InfoPane control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InfoPane As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''TitleLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TitleLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''DescriptionLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DescriptionLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ControlsPane control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ControlsPane As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''RunReportButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RunReportButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ClearReportButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ClearReportButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''VisualizerSection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VisualizerSection As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
