'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3521
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Reports.Visualizers.Xslt

    Partial Public Class Settings

        '''<summary>
        '''lblTransformFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTransformFile As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlTransform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTransform As Global.DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''mvExtensionObjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mvExtensionObjects As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''vwNotAllowed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vwNotAllowed As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''ErrorImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''ErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''vwAllowed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vwAllowed As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''lblExtensionObjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExtensionObjects As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''grdExtensionObjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdExtensionObjects As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''tblAddExtensionObjectForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAddExtensionObjectForm As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblXmlns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblXmlns As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtXmlns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtXmlns As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblClrType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClrType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtClrType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClrType As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnAddExtensionObject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddExtensionObject As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
