'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Reports.Visualizers.Html

    Partial Public Class Settings

        '''<summary>
        '''tblSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblTemplateFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTemplateFile As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTemplate As Global.DotNetNuke.UI.UserControls.UrlControl
    End Class
End Namespace
