'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DotNetNuke.Modules.Reports.DataSources.DotNetNuke

    Partial Public Class Settings

        '''<summary>
        '''SqlDataSourceCommonSettingsControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceCommonSettingsControl As Global.DotNetNuke.Modules.Reports.Controls.SqlDataSourceCommonSettingsControl
    End Class
End Namespace
