'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Reports.DataSources.SqlServer

    Partial Public Class Settings

        '''<summary>
        '''ConnStrModeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConnStrModeLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''AutomaticConnStrRadio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutomaticConnStrRadio As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''AutomaticConnStrLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutomaticConnStrLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ManualConnStrRadio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManualConnStrRadio As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''ManualConnStrLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManualConnStrLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ManualConnStrConfig control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManualConnStrConfig As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''ConnStrLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConnStrLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ConnStrTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConnStrTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''AutomaticConnStrConfig control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutomaticConnStrConfig As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''ServerLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServerLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ServerTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServerTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DatabaseLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DatabaseLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''DatabaseTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DatabaseTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''IntegratedSecurityLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IntegratedSecurityLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''IntegratedSecurityCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IntegratedSecurityCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''UserNameRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserNameRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''UserNameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserNameLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''UserNameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserNameTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PasswordRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PasswordRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''PasswordLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PasswordLabel As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''PasswordTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PasswordTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SqlDataSourceCommonSettingsControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSourceCommonSettingsControl As Global.DotNetNuke.Modules.Reports.Controls.SqlDataSourceCommonSettingsControl
    End Class
End Namespace
