'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Reports.Controls

    Partial Public Class SqlDataSourceCommonSettingsControl

        '''<summary>
        '''QueryUploadLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents QueryUploadLabel As Global.System.Web.UI.UserControl

        '''<summary>
        '''QueryUploadControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents QueryUploadControl As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''QueryUploadButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents QueryUploadButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''QueryLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents QueryLabel As Global.System.Web.UI.UserControl

        '''<summary>
        '''QueryTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents QueryTextBox As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
